<script setup lang="ts">
import { version } from '../../package.json'
</script>

<template>
  <div class="text-center pb-10 text-sm space-x-1">
    <span class="opacity-25">Report generated by</span>
    <a
      href="https://github.com/windicss/windicss-analysis"
      target="_blank"
      class="font-mono opacity-50 cursor-pointer border-b border-transparent hover:(opacity-100 text-primary border-current)"
    >windicss-analysis</a>
    <span class="opacity-25 font-mono">v{{ version }}</span>
  </div>
</template>
